name: Dispatch Event to Other Repos

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 mins
  workflow_dispatch:  # Allow manual execution

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RepoB Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/test-automation-actions/karate-test-demo/actions/workflows/test-execution.yml/dispatches \
            -d '{"ref":"develop"}'

      - name: Trigger RepoC Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/test-automation-actions/karate-test-demo-1/actions/workflows/test-execution.yml/dispatches \
            -d '{"ref":"develop"}'
