name: Master Pipeline

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Enter a custom workflow name'
        required: true
        default: 'Morning Run'

jobs:
  trigger-child-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Workflow Name
        run: echo "WORKFLOW_NAME=${{ github.event.inputs.workflow_name }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Trigger Workflows and Fetch URLs
        id: trigger_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python .github/workflows/scripts/trigger_workflows_name.py --repo "test-automation-actions/karate-test-demo" --workflow "child-workflow.yml" --branch "develop" --workflow-name "${{ env.WORKFLOW_NAME }}"

      - name: Display Triggered Workflow URLs
        run: |
          echo "KARATE_TEST_DEMO Workflow URL: ${{ env.KARATE_TEST_DEMO_URL }}"

