name: Morning Run to Other Repos

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 mins
  workflow_dispatch:  # Allow manual execution
    inputs:
      tags:
        description: "Tags to execute"
        default: ""
        required: false
  

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Trigger Workflows and Fetch URLs
        id: trigger_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python .github/workflows/scripts/trigger_workflows.py --repo "test-automation-actions/karate-test-demo" --workflow "test-execution.yml" --branch "feature/test-inputs" --tags ${{ github.event.inputs.tags }}

      - name: Display Triggered Workflow URLs
        run: |
          echo "KARATE_TEST_DEMO Workflow URL: ${{ env.KARATE_TEST_DEMO_URL }}"
          echo "KARATE_TEST_DEMO_1 Workflow URL: ${{ env.KARATE_TEST_DEMO_1_URL }}"
