name: Morning Run to Other Repos

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 mins
  workflow_dispatch:  # Allow manual execution

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Trigger Workflows and Fetch URLs
        id: trigger_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python .github/scripts/trigger_workflows.py \
            --repo test-automation-actions/karate-test-demo \
            --workflow test-execution.yml \
            --branch develop
            
          python .github/scripts/trigger_workflows.py \
            --repo test-automation-actions/karate-test-demo-1 \
            --workflow test-execution.yml \
            --branch develop

      - name: Display Triggered Workflow URLs
        run: |
          echo "RepoB Workflow URL: ${{ steps.trigger_workflows.outputs.repo_b_url }}"
          echo "RepoC Workflow URL: ${{ steps.trigger_workflows.outputs.repo_c_url }}"
