name: Trigger to karate-test-demo "list-variable" workflow

on:
  # schedule:
  #   - cron: "*/10 * * * *"  # Runs every 10 mins
  workflow_dispatch:  # Allow manual execution

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Trigger Workflows and Fetch URLs
        id: trigger_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python .github/workflows/scripts/trigger_workflows_updated.py --repo "test-automation-actions/karate-test-demo" --workflow "list-variable.yml" --branch "develop" --inputs '{"tags": "1,2,3"}'

      - name: Display Triggered Workflow URLs
        run: |
          echo "KARATE_TEST_DEMO Workflow URL: ${{ env.KARATE_TEST_DEMO_URL }}"
